const TWO_FACTOR_CHALLENGE_PURPOSES = {
  LOGIN: 'login',
};

const TWO_FACTOR_CHALLENGE_PURPOSE_VALUES = Object.values(
  TWO_FACTOR_CHALLENGE_PURPOSES,
);

module.exports = {
  TWO_FACTOR_CHALLENGE_PURPOSES,
  TWO_FACTOR_CHALLENGE_PURPOSE_VALUES,
};
